### ISSUE TITLE
.NET Framework 4.7 Support

### ISSUE THREAD

**Issue by MichaelClaffey** [proff/teamcity-configTransformations#1]
I ran into an issue after upgrading to TeamCity 2017.2 and having the latest .NET Core framework on my build agents.

TeamCity no longer sees the .NET 4.6 framework, just 4.7:
![image](https://user-images.githubusercontent.com/11050521/33564171-d6d9dad4-d8e7-11e7-8fe0-99ee26b2a63c.png)

I modified this line to add 4.7 and all seemed ok after a build:
https://github.com/proff/teamcity-configTransformations/blob/23d16dd3ef5f53f8a25790b05c65a2cc51b4d581/plugin/configTransformations-server/src/main/java/com/proff/teamcity/configTransformations/TransformRunType.kt#L46

**Comment by proff** [comment]
I also found it yesterday, and on the agent where it is installed .net 4.6.1. I will fix this soon, but apparently this is a bug in teamcity

**Comment by yechongbo** [comment]
@Ausweglos can you share the built plugin with that change? thanks!

**Comment by proff** [comment]
@yechongbo, sorry, forgot about it. You can download latest release
https://github.com/proff/teamcity-configTransformations/releases/tag/1.0.1
